/**
 * Vite plugin that mocks Nuxt auto-imports and components for Musea galleries.
 */

import type { Plugin } from "vite";
import type { NuxtMuseaOptions } from "./types.js";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VIRTUAL_IMPORTS_ID = "\0musea-nuxt:imports";
const VIRTUAL_IMPORTS_MODULE = "#imports";
const VIRTUAL_NUXT_COMPONENTS_ID = "\0musea-nuxt:components";

export function createNuxtMuseaPlugin(options: NuxtMuseaOptions = {}): Plugin {
  const srcDir = path.dirname(fileURLToPath(import.meta.url));

  return {
    name: "vite-plugin-musea-nuxt",
    enforce: "pre",

    config() {
      return {
        resolve: {
          alias: {
            // Resolve #imports to our auto-imports module
            "#imports": VIRTUAL_IMPORTS_MODULE,
            // Resolve #app to our auto-imports (subset)
            "#app": VIRTUAL_IMPORTS_MODULE,
            // Resolve #build to empty module
            "#build": VIRTUAL_IMPORTS_MODULE,
          },
        },
      };
    },

    resolveId(id) {
      // Resolve #imports and related aliases
      if (id === VIRTUAL_IMPORTS_MODULE || id === "#imports" || id === "#app" || id === "#build") {
        return VIRTUAL_IMPORTS_ID;
      }

      // Resolve Nuxt component imports
      if (id === "#components" || id === "nuxt/dist/app/components") {
        return VIRTUAL_NUXT_COMPONENTS_ID;
      }

      return null;
    },

    load(id) {
      if (id === VIRTUAL_IMPORTS_ID) {
        return generateImportsModule(srcDir, options);
      }

      if (id === VIRTUAL_NUXT_COMPONENTS_ID) {
        return generateComponentsModule(srcDir);
      }

      return null;
    },

    transform(code, id) {
      // Auto-resolve Nuxt global components in Vue SFC templates
      if (id.endsWith(".vue") || id.endsWith(".art.vue")) {
        // Replace <NuxtLink> with mock component import
        if (code.includes("<NuxtLink") || code.includes("<nuxt-link")) {
          // Check if NuxtLink is already imported
          if (!code.includes("NuxtLink")) {
            const importLine = `import { NuxtLink } from '${VIRTUAL_IMPORTS_MODULE}';\n`;
            // Insert import after last import statement or at the top
            const lastImportIdx = code.lastIndexOf("import ");
            if (lastImportIdx !== -1) {
              const lineEnd = code.indexOf("\n", lastImportIdx);
              code = code.slice(0, lineEnd + 1) + importLine + code.slice(lineEnd + 1);
            }
          }
        }
      }

      return code;
    },
  };
}

function generateImportsModule(srcDir: string, options: NuxtMuseaOptions): string {
  const autoImportsPath = path.join(srcDir, "auto-imports.js").replace(/\\/g, "/");
  const configJson = JSON.stringify(options);

  return `
// Auto-generated by @vizejs/musea-nuxt
export * from '${autoImportsPath}';

// Configure mocks with provided options
import { _setRouteConfig } from '${path.join(srcDir, "mocks", "composables.js").replace(/\\/g, "/")}';
import { _setFetchMocks } from '${path.join(srcDir, "mocks", "data.js").replace(/\\/g, "/")}';
import { _setRuntimeConfig, _setStateMocks } from '${path.join(srcDir, "mocks", "runtime.js").replace(/\\/g, "/")}';

const _config = ${configJson};
_setRouteConfig(_config.route);
_setFetchMocks(_config.fetchMocks ?? {});
_setRuntimeConfig(_config.runtimeConfig);
_setStateMocks(_config.stateMocks ?? {});
`;
}

function generateComponentsModule(srcDir: string): string {
  const componentsPath = path.join(srcDir, "mocks", "components.js").replace(/\\/g, "/");

  return `
// Auto-generated by @vizejs/musea-nuxt
export {
  NuxtLink,
  NuxtPage,
  ClientOnly,
  NuxtLayout,
  NuxtLoadingIndicator,
  NuxtErrorBoundary,
} from '${componentsPath}';
`;
}
