/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'vize-fresco.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.android-arm64.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'vize-fresco.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.android-arm-eabi.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'vize-fresco.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'vize-fresco.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vize-fresco.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'vize-fresco.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vize-fresco.darwin-universal.node')
      } else {
        nativeBinding = require('@vizejs/fresco-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'vize-fresco.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.darwin-x64.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vize-fresco.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.darwin-arm64.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'vize-fresco.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vize-fresco.freebsd-x64.node')
      } else {
        nativeBinding = require('@vizejs/fresco-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-x64-musl.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vize-fresco.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vize-fresco.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@vizejs/fresco-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'vize-fresco.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vize-fresco.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@vizejs/fresco-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { pollEvent, pollEventNonBlocking, readEvent, getImeState, enableIme, disableIme, setImeMode, initLayout, createLayoutNode, createLayoutLeaf, setLayoutRoot, addLayoutChild, removeLayoutChild, setLayoutStyle, removeLayoutNode, computeLayout, getLayout, getAllLayouts, clearLayout, renderText, renderBox, fillRect, clearRect, setCursor, showCursor, hideCursor, setCursorShape, renderTree, initTerminal, initTerminalWithMouse, restoreTerminal, getTerminalInfo, clearScreen, flushTerminal, syncTerminalSize } = nativeBinding

module.exports.pollEvent = pollEvent
module.exports.pollEventNonBlocking = pollEventNonBlocking
module.exports.readEvent = readEvent
module.exports.getImeState = getImeState
module.exports.enableIme = enableIme
module.exports.disableIme = disableIme
module.exports.setImeMode = setImeMode
module.exports.initLayout = initLayout
module.exports.createLayoutNode = createLayoutNode
module.exports.createLayoutLeaf = createLayoutLeaf
module.exports.setLayoutRoot = setLayoutRoot
module.exports.addLayoutChild = addLayoutChild
module.exports.removeLayoutChild = removeLayoutChild
module.exports.setLayoutStyle = setLayoutStyle
module.exports.removeLayoutNode = removeLayoutNode
module.exports.computeLayout = computeLayout
module.exports.getLayout = getLayout
module.exports.getAllLayouts = getAllLayouts
module.exports.clearLayout = clearLayout
module.exports.renderText = renderText
module.exports.renderBox = renderBox
module.exports.fillRect = fillRect
module.exports.clearRect = clearRect
module.exports.setCursor = setCursor
module.exports.showCursor = showCursor
module.exports.hideCursor = hideCursor
module.exports.setCursorShape = setCursorShape
module.exports.renderTree = renderTree
module.exports.initTerminal = initTerminal
module.exports.initTerminalWithMouse = initTerminalWithMouse
module.exports.restoreTerminal = restoreTerminal
module.exports.getTerminalInfo = getTerminalInfo
module.exports.clearScreen = clearScreen
module.exports.flushTerminal = flushTerminal
module.exports.syncTerminalSize = syncTerminalSize
