/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Poll for input events.
 *
 * Returns an event if available within the timeout, or null if no event.
 */
export declare function pollEvent(timeoutMs: number): InputEventNapi | null
/** Poll for input events without blocking. */
export declare function pollEventNonBlocking(): InputEventNapi | null
/** Read an input event, blocking until one is available. */
export declare function readEvent(): InputEventNapi
/** Get current IME state. */
export declare function getImeState(): ImeStateNapi
/** Enable IME. */
export declare function enableIme(): boolean
/** Disable IME. */
export declare function disableIme(): boolean
/** Set IME input mode. */
export declare function setImeMode(mode: string): void
/** Initialize layout engine. */
export declare function initLayout(): void
/** Create a new layout node. */
export declare function createLayoutNode(style?: FlexStyleNapi | undefined | null): number
/** Create a new leaf layout node with measured size. */
export declare function createLayoutLeaf(width: number, height: number, style?: FlexStyleNapi | undefined | null): number
/** Set layout root node. */
export declare function setLayoutRoot(id: number): void
/** Add child to parent node. */
export declare function addLayoutChild(parent: number, child: number): void
/** Remove child from parent node. */
export declare function removeLayoutChild(parent: number, child: number): void
/** Update node style. */
export declare function setLayoutStyle(id: number, style: FlexStyleNapi): void
/** Remove a node. */
export declare function removeLayoutNode(id: number): void
/** Compute layout. */
export declare function computeLayout(width: number, height: number): void
/** Get layout result for a node. */
export declare function getLayout(id: number): LayoutResultNapi | null
/** Get all layout results. */
export declare function getAllLayouts(): Array<LayoutResultNapi>
/** Clear layout engine. */
export declare function clearLayout(): void
/** Render text at position. */
export declare function renderText(x: number, y: number, text: string, style?: StyleNapi | undefined | null): void
/** Render a box (rectangle). */
export declare function renderBox(x: number, y: number, width: number, height: number, border?: string | undefined | null, style?: StyleNapi | undefined | null): void
/** Fill a rectangle with a character. */
export declare function fillRect(x: number, y: number, width: number, height: number, char?: string | undefined | null, style?: StyleNapi | undefined | null): void
/** Clear a rectangular area. */
export declare function clearRect(x: number, y: number, width: number, height: number): void
/** Set cursor position. */
export declare function setCursor(x: number, y: number): void
/** Show cursor. */
export declare function showCursor(): void
/** Hide cursor. */
export declare function hideCursor(): void
/** Set cursor shape. */
export declare function setCursorShape(shape: string): void
/** Render a tree of nodes. */
export declare function renderTree(nodes: Array<RenderNodeNapi>): void
/** Initialize terminal for TUI mode. */
export declare function initTerminal(): void
/** Initialize terminal with mouse capture. */
export declare function initTerminalWithMouse(): void
/** Restore terminal to normal mode. */
export declare function restoreTerminal(): void
/** Get terminal info. */
export declare function getTerminalInfo(): TerminalInfoNapi
/** Clear the screen. */
export declare function clearScreen(): void
/** Flush the terminal buffer. */
export declare function flushTerminal(): void
/** Sync terminal size (call after resize events). */
export declare function syncTerminalSize(): boolean
/** Style options for NAPI. */
export interface StyleNapi {
  /** Foreground color (hex or named) */
  fg?: string
  /** Background color (hex or named) */
  bg?: string
  /** Bold text */
  bold?: boolean
  /** Dim text */
  dim?: boolean
  /** Italic text */
  italic?: boolean
  /** Underline text */
  underline?: boolean
  /** Strikethrough text */
  strikethrough?: boolean
}
/**
 * Flex style options for NAPI.
 * NAPI automatically converts JavaScript camelCase to Rust snake_case.
 */
export interface FlexStyleNapi {
  display?: string
  flexDirection?: string
  flexWrap?: string
  justifyContent?: string
  alignItems?: string
  alignSelf?: string
  alignContent?: string
  flexGrow?: number
  flexShrink?: number
  width?: string
  height?: string
  minWidth?: string
  minHeight?: string
  maxWidth?: string
  maxHeight?: string
  padding?: number
  paddingTop?: number
  paddingRight?: number
  paddingBottom?: number
  paddingLeft?: number
  margin?: number
  marginTop?: number
  marginRight?: number
  marginBottom?: number
  marginLeft?: number
  gap?: number
}
/** Render node for NAPI. */
export interface RenderNodeNapi {
  /** Node ID */
  id: number
  /** Node type: "box" | "text" | "input" */
  nodeType: string
  /** Text content (for text nodes) */
  text?: string
  /** Whether text should wrap */
  wrap?: boolean
  /** Input value (for input nodes) */
  value?: string
  /** Placeholder text (for input nodes) */
  placeholder?: string
  /** Whether input is focused */
  focused?: boolean
  /** Cursor position in input */
  cursor?: number
  /** Whether to mask input (password) */
  mask?: boolean
  /** Flex style */
  style?: FlexStyleNapi
  /** Visual appearance */
  appearance?: StyleNapi
  /** Border style: "none" | "single" | "double" | "rounded" | "heavy" */
  border?: string
  /** Child node IDs */
  children?: Array<number>
}
/** Layout result for NAPI. */
export interface LayoutResultNapi {
  /** Node ID */
  id: number
  /** X position */
  x: number
  /** Y position */
  y: number
  /** Width */
  width: number
  /** Height */
  height: number
}
/** Input event for NAPI. */
export interface InputEventNapi {
  /** Event type: "key" | "mouse" | "resize" | "focus" | "paste" */
  eventType: string
  /** Key code (for key events) */
  key?: string
  /** Character (for key events) */
  char?: string
  /** Modifiers: { ctrl, alt, shift, meta } */
  modifiers?: ModifiersNapi
  /** Mouse button (for mouse events) */
  button?: string
  /** Mouse x position */
  x?: number
  /** Mouse y position */
  y?: number
  /** New width (for resize events) */
  width?: number
  /** New height (for resize events) */
  height?: number
  /** Pasted text (for paste events) */
  text?: string
}
/** Key modifiers for NAPI. */
export interface ModifiersNapi {
  ctrl: boolean
  alt: boolean
  shift: boolean
  meta: boolean
}
/** IME state for NAPI. */
export interface ImeStateNapi {
  /** Whether IME is active */
  active: boolean
  /** Current input mode */
  mode: string
  /** Whether currently composing */
  composing: boolean
  /** Preedit text */
  preedit?: string
  /** Cursor position in preedit */
  preeditCursor?: number
  /** Candidate list */
  candidates?: Array<string>
  /** Selected candidate index */
  selected?: number
}
/** Terminal info for NAPI. */
export interface TerminalInfoNapi {
  /** Terminal width in columns */
  width: number
  /** Terminal height in rows */
  height: number
  /** Whether colors are supported */
  colors: boolean
  /** Whether true color (24-bit) is supported */
  trueColor: boolean
}
